version: '3.8'

services:
  ChatApp:
    image: chatapp
    build: .
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - ChatAppMongoDB

  ChatAppMongoDB:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: