services:
  ChatAppNextJsFrontend:
    depends_on:
      - ChatAppDotNetBackend
    image: ghcr.io/mssbabou/chatapp/nextjs-frontend:latest
    ports:
      - "80:80"
    networks:
      - chat-app-network

  ChatAppDotNetBackend:
    depends_on:
      - ChatAppMongoDB
    image: ghcr.io/mssbabou/chatapp/dotnet-backend:latest
    volumes:
      - chatapp_filestorage:/attachments
    ports:
      - "5001:5001"
    networks:
      - chat-app-network

  ChatAppMongoDB:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chat-app-network

volumes:
  chatapp_filestorage:
  mongodb_data:
  
networks:
  chat-app-network: {}