services:
  ChatAppReactFrontend:
    build: ./React-Frontend/
    image: chatappreactfrontend
    ports:
      - "80:80"
    networks:
      - chat-app-network

  ChatAppDotNetBackend:
    depends_on:
      - ChatAppMongoDB
    build: ./DotNet-Backend/
    image: chatappdotnetbackend
    ports:
      - "5001:5001"
    networks:
      - chat-app-network

  ChatAppMongoDB:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chat-app-network

volumes:
  mongodb_data:

networks:
  chat-app-network: {}
