version: '3.8'

services:
  ChatApp:
    depends_on:
      - ChatAppMongoDB
    build: /ASP.NET-Backend/
    image: chatapp
    ports:
      - "80:80"
    networks:
      - chat-app-network

  ChatAppMongoDB:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chat-app-network

volumes:
  mongodb_data:

networks:
  chat-app-network: {}
