# Step 1: Build the Next.js application
# Use a Node.js base image
FROM node:22.2-alpine as builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN npm run build

# Step 2: Set up the Nginx server
# Use an Nginx base image
FROM nginx:1.26.0-alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d

# Copy the built static files from the builder stage
COPY --from=builder /app/out /usr/share/nginx/html

# Expose the port Nginx is listening on
EXPOSE 80

# Set the backend URL as an environment variable
ENV BACKEND_URL=ChatAppDotNetBackend:5001
ENV DOCKER_ENV=true

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]