name: Build and Push Next.js Frontend Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare tags
        id: prep
        run: |
          REPO_NAME="${{ github.repository }}"
          VERSION="${{ github.event.inputs.version }}"
          REPO_NAME_LOWER=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          VERSION_LOWER=$(echo $VERSION | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_LOWER=${REPO_NAME_LOWER}" >> $GITHUB_ENV
          echo "VERSION_LOWER=${VERSION_LOWER}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./React-Frontend
          file: ./React-Frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_NAME_LOWER }}/nextjs-frontend:${{ env.VERSION_LOWER }}
