name: DotNet Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore DotNet-Backend/
    - name: Build
      run: dotnet build DotNet-Backend/ --no-restore
    - name: Test
      run: dotnet test DotNet-Backend/ --no-build --verbosity normal
